<?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?>

<!DOCTYPE animation [
	<!ELEMENT animation  (frame+)>
	<!ELEMENT frame      (transform+)>
	<!ELEMENT transform   EMPTY>
	<!ATTLIST frame index CDATA #REQUIRED>
	<!ATTLIST transform name CDATA #REQUIRED>
	<!ATTLIST transform m00 CDATA #REQUIRED>
	<!ATTLIST transform m01 CDATA #REQUIRED>
	<!ATTLIST transform m02 CDATA #REQUIRED>
	<!ATTLIST transform m03 CDATA #REQUIRED>
	<!ATTLIST transform m10 CDATA #REQUIRED>
	<!ATTLIST transform m11 CDATA #REQUIRED>
	<!ATTLIST transform m12 CDATA #REQUIRED>
	<!ATTLIST transform m13 CDATA #REQUIRED>
	<!ATTLIST transform m20 CDATA #REQUIRED>
	<!ATTLIST transform m21 CDATA #REQUIRED>
	<!ATTLIST transform m22 CDATA #REQUIRED>
	<!ATTLIST transform m23 CDATA #REQUIRED>
	<!ATTLIST transform m30 CDATA #REQUIRED>
	<!ATTLIST transform m31 CDATA #REQUIRED>
	<!ATTLIST transform m32 CDATA #REQUIRED>
	<!ATTLIST transform m33 CDATA #REQUIRED>
]>

<animation>
	<frame index="0">
		<transform name="Bip01 R Thigh"
			m00="0.71825" m10="0.69541" m20="-0.0228263" m30="0.0136534"
			m01="-0.122373" m11="0.0939604" m21="-0.988026" m31="-0.382742"
			m02="-0.684939" m12="0.712443" m22="0.152586" m32="1.20703"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 Pelvis"
			m00="0.670518" m10="0.741285" m20="0.0300455" m30="0.0183182"
			m01="-0.235885" m11="0.17462" m21="0.955963" m31="-0.23432"
			m02="0.703394" m12="-0.648078" m22="0.291943" m32="1.25236"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 Tail"
			m00="-0.905613" m10="-0.424097" m20="-0.0025998" m30="-0.10625"
			m01="0.0867162" m11="-0.191167" m21="0.97772" m31="-0.258154"
			m02="-0.415145" m12="0.88521" m22="0.209899" m32="1.34316"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 L Thigh"
			m00="-0.370808" m10="0.501044" m20="0.781957" m30="0.0229831"
			m01="0.631495" m11="0.753405" m21="-0.18329" m31="-0.085898"
			m02="-0.680966" m12="0.425836" m22="-0.595775" m32="1.29768"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 Spine"
			m00="0.54686" m10="0.78567" m20="-0.289253" m30="0.119876"
			m01="-0.0194568" m11="0.357324" m21="0.933778" m31="-0.270142"
			m02="0.836998" m12="-0.505018" m22="0.210693" m32="1.35909"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 L Calf"
			m00="-0.614556" m10="0.104235" m20="0.781957" m30="-0.220134"
			m01="-0.0668674" m11="0.980782" m21="-0.18329" m31="0.328136"
			m02="-0.786034" m12="-0.16493" m22="-0.595775" m32="0.851214"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 L Foot"
			m00="-0.171345" m10="0.509922" m20="0.842983" m30="-0.615096"
			m01="-0.225736" m11="0.812555" m21="-0.537399" m31="0.285161"
			m02="-0.959002" m12="-0.282373" m22="-0.0241193" m32="0.346046"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 Spine2"
			m00="0.0871723" m10="0.63483" m20="-0.767718" m30="0.287639"
			m01="0.272013" m11="0.726198" m21="0.631383" m31="-0.244397"
			m02="0.958337" m12="-0.263869" m22="-0.109378" m32="1.69159"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 L UpperArm"
			m00="-0.954859" m10="-0.296518" m20="0.0179041" m30="0.102526"
			m01="0.234295" m11="-0.714693" m21="0.659029" m31="-0.0273466"
			m02="-0.182618" m12="0.633475" m22="0.751904" m32="1.84358"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 L Clavicle"
			m00="-0.76772" m10="-0.634897" m20="0.0866667" m30="0.232162"
			m01="0.631381" m11="-0.726416" m21="0.271435" m31="-0.133961"
			m02="-0.109377" m12="0.263106" m22="0.958547" m32="1.86205"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 Neck"
			m00="0.462186" m10="0.443837" m20="-0.767719" m30="0.30401"
			m01="0.663844" m11="0.400833" m21="0.631382" m31="-0.193165"
			m02="0.587958" m12="-0.801462" m22="-0.109379" m32="1.87242"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 Head"
			m00="0.188551" m10="0.977617" m20="0.0933498" m30="0.391251"
			m01="0.417688" m11="-0.16586" m21="0.893324" m31="-0.0678596"
			m02="0.888811" m12="-0.129446" m22="-0.439612" m32="1.9834"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 Spine1"
			m00="0.343921" m10="0.748858" m20="-0.566506" m30="0.222883"
			m01="0.157008" m11="0.548954" m21="0.820974" m31="-0.273894"
			m02="0.925779" m12="-0.371296" m22="0.0712203" m32="1.51698"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 Ponytail1"
			m00="-0.873448" m10="-0.431582" m20="-0.225444" m30="0.401726"
			m01="-0.348438" m11="0.230597" m21="0.908524" m31="0.155923"
			m02="-0.340116" m12="0.872102" m22="-0.351795" m32="2.44023"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 L Toe0"
			m00="0.533785" m10="0.0667273" m20="0.842983" m30="-0.434896"
			m01="0.841193" m11="0.0599706" m21="-0.537399" m31="0.583091"
			m02="-0.0864134" m12="0.995967" m22="-0.0241192" m32="0.00601099"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 R Toe0"
			m00="0.991089" m10="0.0897467" m20="-0.0984291" m30="0.551063"
			m01="-0.098028" m11="-0.00887717" m21="-0.995144" m31="-0.578243"
			m02="-0.0901846" m12="0.995925" m22="-3.8806e-007" m32="0.00358836"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 L ForeTwist"
			m00="-0.421645" m10="-0.903608" m20="0.0755476" m30="-0.29461"
			m01="0.68686" m11="-0.263888" m21="0.67719" m31="0.0700993"
			m02="-0.591978" m12="0.337425" m22="0.731919" m32="1.76763"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 L Hand"
			m00="-0.269932" m10="-0.375766" m20="-0.886531" m30="-0.507014"
			m01="0.947875" m11="-0.265606" m21="-0.17603" m31="0.416104"
			m02="-0.169321" m12="-0.887836" m22="0.427875" m32="1.46942"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 L Forearm"
			m00="-0.421645" m10="-0.906584" m20="0.0179041" m30="-0.29461"
			m01="0.68686" m11="-0.306438" m21="0.659029" m31="0.0700993"
			m02="-0.591978" m12="0.290174" m22="0.751904" m32="1.76763"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 Prop3"
			m00="-0.866391" m10="-0.496837" m20="0.0501888" m30="0.150361"
			m01="-0.470608" m11="0.845978" m21="0.250699" m31="-0.216767"
			m02="-0.167015" m12="0.193584" m22="-0.966763" m32="1.18129"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 R Calf"
			m00="-0.562342" m10="0.82659" m20="-0.0228263" m30="0.484567"
			m01="-0.113503" m11="-0.104502" m21="-0.988026" m31="-0.462974"
			m02="-0.819078" m12="-0.553018" m22="0.152586" m32="0.757957"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 R Foot"
			m00="1.32347e-006" m10="0.995144" m20="-0.0984291" m30="0.123162"
			m01="2.11176e-007" m11="-0.0984291" m21="-0.995144" m31="-0.53592"
			m02="-1.0" m12="1.29772e-006" m22="-3.44349e-007" m32="0.231552"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 R UpperArm"
			m00="0.145336" m10="-0.852497" m20="-0.502123" m30="0.505628"
			m01="-0.790855" m11="-0.405051" m21="0.458783" m31="-0.358862"
			m02="-0.594496" m12="0.330429" m22="-0.733069" m32="1.90101"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 R Clavicle"
			m00="0.76772" m10="-0.634897" m20="-0.0866668" m30="0.375992"
			m01="-0.631381" m11="-0.726416" m21="-0.271435" m31="-0.252248"
			m02="0.109377" m12="0.263106" m22="-0.958547" m32="1.88254"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 R ForeTwist"
			m00="0.852899" m10="0.107988" m20="-0.510785" m30="0.566075"
			m01="0.402839" m11="-0.758464" m21="0.512302" m31="-0.687787"
			m02="-0.33209" m12="-0.642706" m22="-0.690395" m32="1.65376"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 R Hand"
			m00="0.391588" m10="-0.882595" m20="-0.260164" m30="0.995722"
			m01="0.811093" m11="0.197581" m21="0.550537" m31="-0.484857"
			m02="-0.434497" m12="-0.4266" m22="0.793237" m32="1.48647"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 R Forearm"
			m00="0.852899" m10="0.142952" m20="-0.502123" m30="0.566075"
			m01="0.402839" m11="-0.791984" m21="0.458783" m31="-0.687787"
			m02="-0.33209" m12="-0.59357" m22="-0.733069" m32="1.65376"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 R Finger1"
			m00="-0.647545" m10="-0.760202" m20="-0.0527083" m30="1.16614"
			m01="0.556" m11="-0.518638" m21="0.649522" m31="-0.131877"
			m02="-0.521104" m12="0.391289" m22="0.758514" m32="1.29738"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 R Finger0"
			m00="-0.828689" m10="0.054916" m20="-0.557009" m30="0.979382"
			m01="0.495524" m11="-0.390749" m21="-0.775739" m31="-0.1776"
			m02="-0.260251" m12="-0.918858" m22="0.296597" m32="1.56311"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 R Finger01"
			m00="-0.244718" m10="0.793633" m20="-0.557009" m30="0.810897"
			m01="-0.187966" m11="-0.60241" m21="-0.775739" m31="-0.076853"
			m02="-0.9512" m12="-0.0851384" m22="0.296597" m32="1.5102"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 R Finger11"
			m00="-0.876861" m10="0.477846" m20="-0.0527083" m30="1.02123"
			m01="-0.393566" m11="-0.650559" m21="0.649522" m31="-0.00745933"
			m02="0.276082" m12="0.590284" m22="0.758514" m32="1.18077"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 L Finger1"
			m00="-0.438335" m10="0.104311" m20="-0.892738" m30="-0.624486"
			m01="0.613458" m11="-0.691207" m21="-0.381971" m31="0.828611"
			m02="-0.656911" m12="-0.715089" m22="0.238989" m32="1.39573"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 L Finger0"
			m00="0.245981" m10="-0.946125" m20="-0.210572" m30="-0.371882"
			m01="0.274035" m11="-0.1405" m21="0.951401" m31="0.644653"
			m02="-0.92973" m12="-0.29173" m22="0.224712" m32="1.29606"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 L Finger01"
			m00="-0.177871" m10="-0.96126" m20="-0.210572" m30="-0.32187"
			m01="0.188741" m11="-0.243336" m21="0.951401" m31="0.700368"
			m02="-0.965784" m12="0.129483" m22="0.224712" m32="1.10703"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 L Finger11"
			m00="-0.214314" m10="0.396343" m20="-0.892738" m30="-0.722573"
			m01="-0.106593" m11="-0.918006" m21="-0.381971" m31="0.965886"
			m02="-0.970931" m12="0.0132981" m22="0.238989" m32="1.24874"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 Tail2"
			m00="-0.472156" m10="-0.881246" m20="0.0217615" m30="-0.659557"
			m01="0.039281" m11="0.00362868" m21="0.999222" m31="-0.1989"
			m02="-0.880639" m12="0.472643" m22="0.0329029" m32="0.952091"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 Tail1"
			m00="-0.694821" m10="-0.719178" m20="-0.00286416" m30="-0.419393"
			m01="0.0844754" m11="-0.0855681" m21="0.992745" m31="-0.228127"
			m02="-0.714205" m12="0.689538" m22="0.120207" m32="1.19934"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 Ponytail11"
			m00="-0.799589" m10="-0.308375" m20="-0.515327" m30="0.08719"
			m01="-0.555013" m11="0.0516908" m21="0.830234" m31="0.0303976"
			m02="-0.229386" m12="0.949859" m22="-0.212484" m32="2.31744"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 Ponytail12"
			m00="-0.656278" m10="-0.127988" m20="-0.743585" m30="-0.200793"
			m01="-0.739154" m11="-0.0888161" m21="0.667655" m31="-0.169498"
			m02="-0.151494" m12="0.987791" m22="-0.0363148" m32="2.23453"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 Prop2"
			m00="-0.972362" m10="0.167104" m20="0.163062" m30="0.85734"
			m01="0.0154041" m11="0.74279" m21="-0.669347" m31="0.482592"
			m02="-0.232972" m12="-0.648336" m22="-0.724835" m32="1.94714"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 Prop1"
			m00="0.0" m10="0.0" m20="0.0" m30="0.607593"
			m01="0.0" m11="0.0" m21="0.0" m31="-0.50202"
			m02="0.0" m12="0.0" m22="0.0" m32="1.33275"
			m03="0" m13="0" m23="0" m33="1"/>
	</frame>
	<frame index="1">
		<transform name="Bip01 R Thigh"
			m00="0.73983" m10="0.672583" m20="-0.0168324" m30="0.00328019"
			m01="-0.117163" m11="0.104161" m21="-0.987635" m31="-0.382742"
			m02="-0.662513" m12="0.732655" m22="0.155863" m32="1.18923"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 Pelvis"
			m00="0.680846" m10="0.73181" m20="0.0300456" m30="0.00794504"
			m01="-0.233413" m11="0.17791" m21="0.955963" m31="-0.23432"
			m02="0.694238" m12="-0.657877" m22="0.291943" m32="1.23455"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 Tail"
			m00="-0.911444" m10="-0.411408" m20="-0.00378537" m30="-0.115296"
			m01="0.0831693" m11="-0.193251" m21="0.977618" m31="-0.2587"
			m02="-0.402931" m12="0.890729" m22="0.210354" m32="1.32701"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 L Thigh"
			m00="-0.371252" m10="0.507371" m20="0.777655" m30="0.0126099"
			m01="0.63979" m11="0.746745" m21="-0.181768" m31="-0.085898"
			m02="-0.672934" m12="0.430054" m22="-0.601842" m32="1.27988"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 Spine"
			m00="0.568752" m10="0.769606" m20="-0.29022" m30="0.111072"
			m01="-0.0125798" m11="0.360945" m21="0.932502" m31="-0.269768"
			m02="0.822413" m12="-0.526711" m22="0.21497" m32="1.33991"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 L Calf"
			m00="-0.621289" m10="0.0961936" m20="0.777655" m30="-0.230798"
			m01="-0.075718" m11="0.980422" m21="-0.181768" m31="0.333574"
			m02="-0.779915" m12="-0.171813" m22="-0.601842" m32="0.838678"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 L Foot"
			m00="-0.148411" m10="0.532626" m20="0.833237" m30="-0.630088"
			m01="-0.211988" m11="0.805847" m21="-0.552876" m31="0.284912"
			m02="-0.965937" m12="-0.258689" m22="-0.00668573" m32="0.337443"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 Spine2"
			m00="0.129256" m10="0.616731" m20="-0.776489" m30="0.289215"
			m01="0.293724" m11="0.724105" m21="0.624018" m31="-0.240204"
			m02="0.947111" m12="-0.308731" m22="-0.0875542" m32="1.66676"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 L UpperArm"
			m00="-0.914578" m10="-0.402117" m20="0.0430119" m30="0.109735"
			m01="0.318453" m11="-0.650543" m21="0.68948" m31="-0.0209934"
			m02="-0.24927" m12="0.64428" m22="0.723027" m32="1.82237"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 L Clavicle"
			m00="-0.776491" m10="-0.616832" m20="0.128764" m30="0.240852"
			m01="0.624016" m11="-0.72434" m21="0.293147" m31="-0.126364"
			m02="-0.0875534" m12="0.307977" m22="0.947356" m32="1.83715"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 Neck"
			m00="0.468036" m10="0.421907" m20="-0.77649" m30="0.313525"
			m01="0.664186" m11="0.411655" m21="0.624017" m31="-0.184879"
			m02="0.582924" m12="-0.807796" m22="-0.0875556" m32="1.84547"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 Head"
			m00="0.233475" m10="0.970084" m20="0.0665343" m30="0.40187"
			m01="0.438155" m11="-0.166044" m21="0.88343" m31="-0.05951"
			m02="0.868049" m12="-0.177107" m22="-0.463814" m32="1.95551"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 Spine1"
			m00="0.377049" m10="0.729842" m20="-0.570232" m30="0.218209"
			m01="0.170381" m11="0.550509" m21="0.817258" m31="-0.272223"
			m02="0.910387" m12="-0.405303" m22="0.0832178" m32="1.49505"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 Ponytail1"
			m00="-0.888776" m10="-0.385935" m20="-0.247247" m30="0.435519"
			m01="-0.358429" m11="0.249027" m21="0.89973" m31="0.174552"
			m02="-0.285666" m12="0.888279" m22="-0.35966" m32="2.40602"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 L Toe0"
			m00="0.533785" m10="0.0667274" m20="0.842983" m30="-0.434897"
			m01="0.841193" m11="0.0599706" m21="-0.537399" m31="0.583091"
			m02="-0.0864134" m12="0.995967" m22="-0.0241191" m32="0.00601029"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 R Toe0"
			m00="0.991089" m10="0.0897467" m20="-0.0984291" m30="0.551064"
			m01="-0.098028" m11="-0.00887718" m21="-0.995144" m31="-0.578243"
			m02="-0.0901846" m12="0.995925" m22="-4.166e-007" m32="0.00358842"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 L ForeTwist"
			m00="-0.348293" m10="-0.931171" m20="0.107757" m30="-0.270648"
			m01="0.688644" m11="-0.176183" m21="0.70337" m31="0.111455"
			m02="-0.635973" m12="0.319185" m22="0.702609" m32="1.71869"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 L Hand"
			m00="-0.167152" m10="-0.359053" m20="-0.918227" m30="-0.4461"
			m01="0.95148" m11="-0.30279" m21="-0.0548056" m31="0.458358"
			m02="-0.258352" m12="-0.882836" m22="0.392244" m32="1.39832"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 L Forearm"
			m00="-0.348293" m10="-0.936398" m20="0.0430119" m30="-0.270648"
			m01="0.688644" m11="-0.224471" m21="0.68948" m31="0.111455"
			m02="-0.635973" m12="0.269761" m22="0.723027" m32="1.71869"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 Prop3"
			m00="-0.86662" m10="-0.497654" m20="0.036199" m30="0.13895"
			m01="-0.474087" m11="0.843859" m21="0.251283" m31="-0.216198"
			m02="-0.155599" m12="0.200606" m22="-0.967236" m32="1.16173"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 R Calf"
			m00="-0.568216" m10="0.822707" m20="-0.0168324" m30="0.488343"
			m01="-0.118817" m11="-0.10227" m21="-0.987635" m31="-0.459559"
			m02="-0.814256" m12="-0.55919" m22="0.155863" m32="0.754858"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 R Foot"
			m00="1.29999e-006" m10="0.995144" m20="-0.0984291" m30="0.123163"
			m01="1.78544e-007" m11="-0.0984291" m21="-0.995144" m31="-0.53592"
			m02="-1.0" m12="1.28587e-006" m22="-3.2946e-007" m32="0.231552"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 R UpperArm"
			m00="0.205617" m10="-0.879786" m20="-0.428601" m30="0.517442"
			m01="-0.820758" m11="-0.393553" m21="0.414092" m31="-0.348642"
			m02="-0.53299" m12="0.266633" m22="-0.803012" m32="1.86834"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 R Clavicle"
			m00="0.776491" m10="-0.616832" m20="-0.128764" m30="0.386324"
			m01="-0.624016" m11="-0.72434" m21="-0.293147" m31="-0.243271"
			m02="0.0875533" m12="0.307977" m22="-0.947356" m32="1.85355"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 R ForeTwist"
			m00="0.885636" m10="0.133338" m20="-0.444825" m30="0.60296"
			m01="0.36839" m11="-0.784931" m21="0.498169" m31="-0.690003"
			m02="-0.282732" m12="-0.605066" m22="-0.744284" m32="1.64666"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 R Hand"
			m00="0.479043" m10="-0.843239" m20="-0.243857" m30="1.0491"
			m01="0.778804" m11="0.280132" m21="0.56124" m31="-0.504427"
			m02="-0.404947" m12="-0.458774" m22="0.790913" m32="1.50424"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 R Forearm"
			m00="0.885636" m10="0.178745" m20="-0.428601" m30="0.60296"
			m01="0.36839" m11="-0.832356" m21="0.414092" m31="-0.690003"
			m02="-0.282732" m12="-0.524627" m22="-0.803012" m32="1.64666"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 R Finger1"
			m00="-0.573917" m10="-0.81846" m20="-0.0272492" m30="1.25757"
			m01="0.61757" m11="-0.454423" m21="0.641955" m31="-0.165499"
			m02="-0.537797" m12="0.351601" m22="0.766258" m32="1.32801"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 R Finger0"
			m00="-0.770424" m10="0.0588485" m20="-0.63481" m30="1.05657"
			m01="0.570016" m11="-0.382373" m21="-0.727236" m31="-0.197926"
			m02="-0.285531" m12="-0.922132" m22="0.261045" m32="1.58516"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 R Finger01"
			m00="-0.220233" m10="0.740617" m20="-0.63481" m30="0.899932"
			m01="-0.153534" m11="-0.668996" m21="-0.727236" m31="-0.0820329"
			m02="-0.963288" m12="-0.0626959" m22="0.261045" m32="1.52711"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 R Finger11"
			m00="-0.918777" m10="0.393834" m20="-0.0272492" m30="1.12915"
			m01="-0.318087" m11="-0.697649" m21="0.641955" m31="-0.0273033"
			m02="0.233814" m12="0.598482" m22="0.766258" m32="1.20766"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 L Finger1"
			m00="-0.347634" m10="0.0545039" m20="-0.936045" m30="-0.518844"
			m01="0.624229" m11="-0.731458" m21="-0.274421" m31="0.872434"
			m02="-0.699635" m12="-0.679704" m22="0.220257" m32="1.28589"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 L Finger0"
			m00="0.303311" m10="-0.944545" m20="-0.125844" m30="-0.281302"
			m01="0.169377" m11="-0.0765204" m21="0.982576" m31="0.657693"
			m02="-0.937717" m12="-0.319342" m22="0.136774" m32="1.21487"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 L Finger01"
			m00="-0.113459" m10="-0.98554" m20="-0.125844" m30="-0.219634"
			m01="0.122711" m11="-0.139592" m21="0.982576" m31="0.69213"
			m02="-0.985936" m12="0.0960399" m22="0.136774" m32="1.02422"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 L Finger11"
			m00="-0.202641" m10="0.287674" m20="-0.936045" m30="-0.596635"
			m01="-0.09134" m11="-0.957262" m21="-0.274421" m31="1.01212"
			m02="-0.974984" m12="0.0298894" m22="0.220257" m32="1.12933"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 Tail2"
			m00="-0.484075" m10="-0.874839" m20="0.0181129" m30="-0.674033"
			m01="0.0376934" m11="-0.000167343" m21="0.999289" m31="-0.201559"
			m02="-0.874214" m12="0.484414" m22="0.0330567" m32="0.943418"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 Tail1"
			m00="-0.704672" m10="-0.709514" m20="-0.00531347" m30="-0.430459"
			m01="0.0819098" m11="-0.0887849" m21="0.992677" m31="-0.229899"
			m02="-0.70479" m12="0.699076" m22="0.12068" m32="1.18741"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 Ponytail11"
			m00="-0.808372" m10="-0.258097" m20="-0.529076" m30="0.115448"
			m01="-0.562249" m11="0.0722609" m21="0.823805" m31="0.0454215"
			m02="-0.17439" m12="0.963413" m22="-0.203529" m32="2.30284"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 Ponytail12"
			m00="-0.66043" m10="-0.0754097" m20="-0.747091" m30="-0.175714"
			m01="-0.74419" m11="-0.0668568" m21="0.664614" m31="-0.157086"
			m02="-0.100066" m12="0.994909" m22="-0.011965" m32="2.23974"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 Prop2"
			m00="-0.95666" m10="0.258582" m20="0.133933" m30="0.976925"
			m01="0.104148" m11="0.733308" m21="-0.671872" m31="0.465534"
			m02="-0.271948" m12="-0.628804" m22="-0.728457" m32="1.97466"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 Prop1"
			m00="0.0" m10="0.0" m20="0.0" m30="0.659018"
			m01="0.0" m11="0.0" m21="0.0" m31="-0.523119"
			m02="0.0" m12="0.0" m22="0.0" m32="1.35573"
			m03="0" m13="0" m23="0" m33="1"/>
	</frame>
	<frame index="2">
		<transform name="Bip01 R Thigh"
			m00="0.760539" m10="0.649202" m20="-0.010866" m30="-0.00709301"
			m01="-0.11164" m11="0.114263" m21="-0.987158" m31="-0.382742"
			m02="-0.639623" m12="0.751985" m22="0.159379" m32="1.17143"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 Pelvis"
			m00="0.69104" m10="0.722192" m20="0.0300456" m30="-0.00242817"
			m01="-0.230896" m11="0.181165" m21="0.955963" m31="-0.23432"
			m02="0.684946" m12="-0.667547" m22="0.291943" m32="1.21675"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 Tail"
			m00="-0.917096" m10="-0.398636" m20="-0.0049643" m30="-0.124318"
			m01="0.0795938" m11="-0.195285" m21="0.977511" m31="-0.259241"
			m02="-0.390641" m12="0.896076" m22="0.210824" m32="1.31084"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 L Thigh"
			m00="-0.371023" m10="0.513992" m20="0.773405" m30="0.00223668"
			m01="0.648378" m11="0.739614" m21="-0.180491" m31="-0.085898"
			m02="-0.664792" m12="0.434492" m22="-0.607675" m32="1.26208"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 Spine"
			m00="0.590813" m10="0.752453" m20="-0.291125" m30="0.102247"
			m01="-0.00525717" m11="0.364418" m21="0.931221" m31="-0.269387"
			m02="0.806791" m12="-0.548647" m22="0.219259" m32="1.3207"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 L Calf"
			m00="-0.627688" m10="0.0886171" m20="0.773405" m30="-0.241021"
			m01="-0.0840377" m11="0.97998" m21="-0.180491" m31="0.339205"
			m02="-0.773916" m12="-0.178287" m22="-0.607675" m32="0.826215"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 L Foot"
			m00="-0.12585" m10="0.554004" m20="0.822946" m30="-0.644423"
			m01="-0.199367" m11="0.798494" m21="-0.568032" m31="0.285196"
			m02="-0.97181" m12="-0.235555" m22="0.00995967" m32="0.328835"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 Spine2"
			m00="0.172056" m10="0.595434" m20="-0.784765" m30="0.290884"
			m01="0.316997" m11="0.720804" m21="0.616404" m31="-0.235736"
			m02="0.93269" m12="-0.354824" m22="-0.0647321" m32="1.64132"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 L UpperArm"
			m00="-0.862534" m10="-0.500823" m20="0.0721842" m30="0.117302"
			m01="0.394067" m11="-0.575377" m21="0.716696" m31="-0.0141363"
			m02="-0.317405" m12="0.64662" m22="0.69364" m32="1.8002"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 L Clavicle"
			m00="-0.784766" m10="-0.595568" m20="0.171581" m30="0.249817"
			m01="0.616402" m11="-0.721058" m21="0.316423" m31="-0.118221"
			m02="-0.0647312" m12="0.354081" m22="0.932972" m32="1.81113"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 Neck"
			m00="0.473981" m10="0.399357" m20="-0.784765" m30="0.323268"
			m01="0.664156" m11="0.423017" m21="0.616403" m31="-0.176025"
			m02="0.578134" m12="-0.81337" m22="-0.0647334" m32="1.81732"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 Head"
			m00="0.279731" m10="0.959336" m20="0.0377398" m30="0.412735"
			m01="0.459618" m11="-0.168324" m21="0.87202" m31="-0.0506612"
			m02="0.842913" m12="-0.226585" m22="-0.488013" m32="1.92644"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 Spine1"
			m00="0.410606" m10="0.708679" m20="-0.57374" m30="0.213548"
			m01="0.184727" m11="0.551528" m21="0.813445" m31="-0.270461"
			m02="0.892905" m12="-0.439991" m22="0.0955482" m32="1.4729"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 Ponytail1"
			m00="-0.902021" m10="-0.336962" m20="-0.269841" m30="0.470504"
			m01="-0.367085" m11="0.269774" m21="0.890208" m31="0.194359"
			m02="-0.22717" m12="0.902041" m22="-0.367036" m32="2.36861"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 L Toe0"
			m00="0.533785" m10="0.0667275" m20="0.842983" m30="-0.434896"
			m01="0.841193" m11="0.0599706" m21="-0.537399" m31="0.583091"
			m02="-0.0864135" m12="0.995967" m22="-0.0241192" m32="0.0060111"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 R Toe0"
			m00="0.991089" m10="0.0897467" m20="-0.0984291" m30="0.551064"
			m01="-0.098028" m11="-0.00887718" m21="-0.995144" m31="-0.578243"
			m02="-0.0901847" m12="0.995925" m22="-4.1843e-007" m32="0.0035884"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 L ForeTwist"
			m00="-0.273873" m10="-0.950997" m20="0.143523" m30="-0.241435"
			m01="0.682965" m11="-0.0872349" m21="0.725223" m31="0.14976"
			m02="-0.677165" m12="0.29664" m22="0.673388" m32="1.66819"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 L Hand"
			m00="-0.0603438" m10="-0.349103" m20="-0.935139" m30="-0.379399"
			m01="0.937802" m11="-0.340708" m21="0.0666766" m31="0.493803"
			m02="-0.341887" m12="-0.872952" m22="0.347949" m32="1.32707"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 L Forearm"
			m00="-0.273873" m10="-0.959053" m20="0.0721842" m30="-0.241435"
			m01="0.682965" m11="-0.141089" m21="0.716696" m31="0.14976"
			m02="-0.677165" m12="0.245583" m22="0.69364" m32="1.66819"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 Prop3"
			m00="-0.866681" m10="-0.498368" m20="0.0222019" m30="0.127514"
			m01="-0.477572" m11="0.841734" m21="0.251811" m31="-0.215633"
			m02="-0.144182" m12="0.207637" m22="-0.967522" m32="1.14219"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 R Calf"
			m00="-0.573202" m10="0.819342" m20="-0.010866" m30="0.491547"
			m01="-0.124452" m11="-0.100157" m21="-0.987158" m31="-0.455937"
			m02="-0.809908" m12="-0.564488" m22="0.159379" m32="0.752063"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 R Foot"
			m00="1.28295e-006" m10="0.995144" m20="-0.0984291" m30="0.123162"
			m01="2.02039e-007" m11="-0.0984291" m21="-0.995144" m31="-0.53592"
			m02="-1.0" m12="1.25435e-006" m22="-3.54471e-007" m32="0.231552"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 R UpperArm"
			m00="0.263509" m10="-0.901687" m20="-0.342817" m30="0.529354"
			m01="-0.84782" m11="-0.386004" m21="0.363595" m31="-0.337787"
			m02="-0.460178" m12="0.194837" m22="-0.866184" m32="1.83419"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 R Clavicle"
			m00="0.784766" m10="-0.595568" m20="-0.171581" m30="0.396839"
			m01="-0.616402" m11="-0.721058" m21="-0.316423" m31="-0.233702"
			m02="0.0647311" m12="0.354081" m22="-0.932972" m32="1.82326"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 R ForeTwist"
			m00="0.915806" m10="0.159031" m20="-0.368794" m30="0.63895"
			m01="0.334719" m11="-0.809695" m21="0.482034" m31="-0.690404"
			m02="-0.221952" m12="-0.564892" m22="-0.794754" m32="1.6428"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 R Hand"
			m00="0.567372" m10="-0.789147" m20="-0.235237" m30="1.10029"
			m01="0.741673" m11="0.365603" m21="0.562366" m31="-0.52179"
			m02="-0.357786" m12="-0.493539" m22="0.792722" m32="1.53099"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 R Forearm"
			m00="0.915806" m10="0.209228" m20="-0.342817" m30="0.63895"
			m01="0.334719" m11="-0.869345" m21="0.363595" m31="-0.690404"
			m02="-0.221952" m12="-0.44773" m22="-0.866184" m32="1.6428"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 R Finger1"