<?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?>

<!DOCTYPE mesh [
	<!ELEMENT mesh       (polygons)>
	<!ELEMENT polygons   (polygon+)>
	<!ELEMENT polygon    (vertex+)>
	<!ELEMENT vertex     (skin+)>

	<!ELEMENT skin        EMPTY>

	<!ATTLIST mesh texture CDATA #REQUIRED>
	<!ATTLIST vertex x CDATA #REQUIRED>
	<!ATTLIST vertex y CDATA #REQUIRED>
	<!ATTLIST vertex z CDATA #REQUIRED>
	<!ATTLIST vertex r CDATA #REQUIRED>
	<!ATTLIST vertex g CDATA #REQUIRED>
	<!ATTLIST vertex b CDATA #REQUIRED>
	<!ATTLIST vertex a CDATA #REQUIRED>
	<!ATTLIST vertex nx CDATA #REQUIRED>
	<!ATTLIST vertex ny CDATA #REQUIRED>
	<!ATTLIST vertex nz CDATA #REQUIRED>
	<!ATTLIST vertex u CDATA #REQUIRED>
	<!ATTLIST vertex v CDATA #REQUIRED>
	<!ATTLIST skin bone CDATA #REQUIRED>
	<!ATTLIST skin weight CDATA #REQUIRED>
]>

<mesh texture="trees">
	<polygons>
		<polygon>
			<vertex x="0.238732" y="2.86497" z="3.76267"
				r="1" g="1" b="1" a="1"
				nx="0.84454" ny="-0.535491" nz="-0.00169454"
				u="0.698557" v="0.427417">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="0.17944" y="1.40752" z="-1.0605"
				r="1" g="1" b="1" a="1"
				nx="0.991956" ny="-0.121424" nz="0.0357732"
				u="0.494947" v="0.00878353">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="-0.0558031" y="0.144294" z="2.06761"
				r="1" g="1" b="1" a="1"
				nx="-0.99798" ny="0.0601317" nz="0.0204725"
				u="0.291337" v="0.427417">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="0.238732" y="2.86497" z="3.76267"
				r="1" g="1" b="1" a="1"
				nx="0.84454" ny="-0.535491" nz="-0.00169454"
				u="0.698557" v="0.427417">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="-0.0558031" y="0.144294" z="2.06761"
				r="1" g="1" b="1" a="1"
				nx="-0.99798" ny="0.0601317" nz="0.0204725"
				u="0.291337" v="0.427417">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="0.17944" y="1.40752" z="-1.0605"
				r="1" g="1" b="1" a="1"
				nx="0.991956" ny="-0.121424" nz="0.0357732"
				u="0.494947" v="0.00878353">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="-1.46503" y="2.65189" z="7.32168"
				r="1" g="1" b="1" a="1"
				nx="-0.65725" ny="0.75151" nz="0.0570529"
				u="0.695658" v="0.490024">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="-0.242479" y="1.14271" z="-0.199712"
				r="1" g="1" b="1" a="1"
				nx="-0.671068" ny="0.740609" nz="0.0341508"
				u="0.495047" v="0.00935154">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="0.0659407" y="-0.0503794" z="5.87637"
				r="1" g="1" b="1" a="1"
				nx="-0.547949" ny="0.835821" nz="-0.0339852"
				u="0.294435" v="0.490024">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="-1.46503" y="2.65189" z="7.32168"
				r="1" g="1" b="1" a="1"
				nx="-0.65725" ny="0.75151" nz="0.0570529"
				u="0.695658" v="0.490024">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="0.0659407" y="-0.0503794" z="5.87637"
				r="1" g="1" b="1" a="1"
				nx="-0.547949" ny="0.835821" nz="-0.0339852"
				u="0.294435" v="0.490024">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="-0.242479" y="1.14271" z="-0.199712"
				r="1" g="1" b="1" a="1"
				nx="-0.671068" ny="0.740609" nz="0.0341508"
				u="0.495047" v="0.00935154">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="-0.759542" y="-1.38305" z="9.06332"
				r="1" g="1" b="1" a="1"
				nx="-0.560394" ny="0.827982" nz="0.0201254"
				u="0.632042" v="0.490024">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="-0.230784" y="-0.549918" z="0.0627517"
				r="1" g="1" b="1" a="1"
				nx="-0.84485" ny="0.535001" nz="0.00138017"
				u="0.495047" v="0.00935154">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="0.0970763" y="-0.0445871" z="7.60498"
				r="1" g="1" b="1" a="1"
				nx="0.500789" ny="-0.849842" nz="0.164251"
				u="0.358051" v="0.490024">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="-0.759542" y="-1.38305" z="9.06332"
				r="1" g="1" b="1" a="1"
				nx="-0.560394" ny="0.827982" nz="0.0201254"
				u="0.632042" v="0.490024">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="0.0970763" y="-0.0445871" z="7.60498"
				r="1" g="1" b="1" a="1"
				nx="0.500789" ny="-0.849842" nz="0.164251"
				u="0.358051" v="0.490024">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="-0.230784" y="-0.549918" z="0.0627517"
				r="1" g="1" b="1" a="1"
				nx="-0.84485" ny="0.535001" nz="0.00138017"
				u="0.495047" v="0.00935154">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="0.0863268" y="-0.226877" z="3.7219"
				r="1" g="1" b="1" a="1"
				nx="-0.71096" ny="0.697224" nz="-0.0917272"
				u="0.695658" v="0.490024">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="0.137939" y="-1.36304" z="-0.948092"
				r="1" g="1" b="1" a="1"
				nx="-0.996663" ny="0.0809039" nz="0.0108312"
				u="0.495047" v="0.00935154">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="0.0125202" y="-2.83935" z="7.09339"
				r="1" g="1" b="1" a="1"
				nx="-0.996109" ny="0.0880893" nz="-0.00276748"
				u="0.294435" v="0.490024">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="0.0863268" y="-0.226877" z="3.7219"
				r="1" g="1" b="1" a="1"
				nx="-0.71096" ny="0.697224" nz="-0.0917272"
				u="0.695658" v="0.490024">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="0.0125202" y="-2.83935" z="7.09339"
				r="1" g="1" b="1" a="1"
				nx="-0.996109" ny="0.0880893" nz="-0.00276748"
				u="0.294435" v="0.490024">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="0.137939" y="-1.36304" z="-0.948092"
				r="1" g="1" b="1" a="1"
				nx="-0.996663" ny="0.0809039" nz="0.0108312"
				u="0.495047" v="0.00935154">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="-1.05539" y="1.25696" z="3.89295"
				r="1" g="1" b="1" a="1"
				nx="-0.435453" ny="-0.897785" nz="-0.0660538"
				u="0.695794" v="0.490139">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="-0.359061" y="1.03442" z="-0.425711"
				r="1" g="1" b="1" a="1"
				nx="-0.471603" ny="-0.880337" nz="-0.0509734"
				u="0.615869" v="0.298636">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="-0.0467997" y="0.657603" z="2.53159"
				r="1" g="1" b="1" a="1"
				nx="0.99972" ny="-0.0220352" nz="0.00857553"
				u="0.535944" v="0.490139">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="-1.05539" y="1.25696" z="3.89295"
				r="1" g="1" b="1" a="1"
				nx="-0.435453" ny="-0.897785" nz="-0.0660538"
				u="0.695794" v="0.490139">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="-0.0467997" y="0.657603" z="2.53159"
				r="1" g="1" b="1" a="1"
				nx="0.99972" ny="-0.0220352" nz="0.00857553"
				u="0.535944" v="0.490139">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="-0.359061" y="1.03442" z="-0.425711"
				r="1" g="1" b="1" a="1"
				nx="-0.471603" ny="-0.880337" nz="-0.0509734"
				u="0.615869" v="0.298636">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="1.6925" y="-1.53607" z="6.34"
				r="1" g="1" b="1" a="1"
				nx="0.315095" ny="-0.940157" nz="-0.129689"
				u="0.614458" v="0.490024">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="0.834771" y="-0.756067" z="-0.867705"
				r="1" g="1" b="1" a="1"
				nx="0.0316972" ny="0.98987" nz="-0.13839"
				u="0.50627" v="0.0130927">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="0.0863268" y="-0.226877" z="3.7219"
				r="1" g="1" b="1" a="1"
				nx="-0.71096" ny="0.697224" nz="-0.0917272"
				u="0.375635" v="0.490024">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="1.6925" y="-1.53607" z="6.34"
				r="1" g="1" b="1" a="1"
				nx="0.315095" ny="-0.940157" nz="-0.129689"
				u="0.614458" v="0.490024">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="0.0863268" y="-0.226877" z="3.7219"
				r="1" g="1" b="1" a="1"
				nx="-0.71096" ny="0.697224" nz="-0.0917272"
				u="0.375635" v="0.490024">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="0.834771" y="-0.756067" z="-0.867705"
				r="1" g="1" b="1" a="1"
				nx="0.0316972" ny="0.98987" nz="-0.13839"
				u="0.50627" v="0.0130927">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="-1.92639" y="0.88269" z="7.8044"
				r="1" g="1" b="1" a="1"
				nx="0.0423059" ny="0.999023" nz="-0.0128042"
				u="0.575839" v="0.490024">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="-0.962265" y="0.814969" z="-0.852947"
				r="1" g="1" b="1" a="1"
				nx="0.330269" ny="-0.943816" nz="0.0115256"
				u="0.495047" v="0.00935154">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="-0.444609" y="0.627798" z="6.13485"
				r="1" g="1" b="1" a="1"
				nx="0.0232878" ny="0.999622" nz="0.0146202"
				u="0.414254" v="0.490024">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="-1.92639" y="0.88269" z="7.8044"
				r="1" g="1" b="1" a="1"
				nx="0.0423059" ny="0.999023" nz="-0.0128042"
				u="0.575839" v="0.490024">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="-0.444609" y="0.627798" z="6.13485"
				r="1" g="1" b="1" a="1"
				nx="0.0232878" ny="0.999622" nz="0.0146202"
				u="0.414254" v="0.490024">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="-0.962265" y="0.814969" z="-0.852947"
				r="1" g="1" b="1" a="1"
				nx="0.330269" ny="-0.943816" nz="0.0115256"
				u="0.495047" v="0.00935154">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="-1.1472" y="0.552285" z="9.57131"
				r="1" g="1" b="1" a="1"
				nx="-0.387947" ny="-0.921674" nz="-0.00375723"
				u="0.590576" v="0.490024">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="-0.491668" y="0.251705" z="0.270374"
				r="1" g="1" b="1" a="1"
				nx="-0.423951" ny="-0.905684" nz="-0.00156792"
				u="0.495047" v="0.00935154">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="-0.0859898" y="0.0456459" z="7.57943"
				r="1" g="1" b="1" a="1"
				nx="0.384553" ny="-0.922995" nz="-0.0141244"
				u="0.399517" v="0.490024">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="-1.1472" y="0.552285" z="9.57131"
				r="1" g="1" b="1" a="1"
				nx="-0.387947" ny="-0.921674" nz="-0.00375723"
				u="0.590576" v="0.490024">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="-0.0859898" y="0.0456459" z="7.57943"
				r="1" g="1" b="1" a="1"
				nx="0.384553" ny="-0.922995" nz="-0.0141244"
				u="0.399517" v="0.490024">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="-0.491668" y="0.251705" z="0.270374"
				r="1" g="1" b="1" a="1"
				nx="-0.423951" ny="-0.905684" nz="-0.00156792"
				u="0.495047" v="0.00935154">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="0.576159" y="2.26985" z="5.99569"
				r="1" g="1" b="1" a="1"
				nx="-0.987755" ny="-0.0648401" nz="0.1419"
				u="0.554576" v="0.127664">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="0.377347" y="3.88992" z="5.35205"
				r="1" g="1" b="1" a="1"
				nx="-2.43359" ny="-0.366968" nz="2.67216"
				u="0.772752" v="0.0160363">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="0.21758" y="2.39418" z="3.55646"
				r="1" g="1" b="1" a="1"
				nx="-0.991142" ny="-0.044394" nz="0.12517"
				u="0.772783" v="0.477891">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="0.377347" y="3.88992" z="5.35205"
				r="1" g="1" b="1" a="1"
				nx="-2.43359" ny="-0.366968" nz="2.67216"
				u="0.772752" v="0.0160363">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="-1.24785" y="4.1152" z="4.60603"
				r="1" g="1" b="1" a="1"
				nx="-0.377374" ny="-0.694745" nz="0.612305"
				u="1.00017" v="0.127542">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="0.21758" y="2.39418" z="3.55646"
				r="1" g="1" b="1" a="1"
				nx="-0.991142" ny="-0.044394" nz="0.12517"
				u="0.772783" v="0.477891">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="-2.95254" y="4.3515" z="3.82352"
				r="1" g="1" b="1" a="1"
				nx="-0.20863" ny="0.712708" nz="0.669717"
				u="0.49293" v="0.00352852">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="0.796203" y="0.476737" z="6.70807"
				r="1" g="1" b="1" a="1"
				nx="0.114621" ny="0.3789" nz="0.918312"
				u="0.249741" v="0.489905">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="0.377347" y="3.88992" z="5.35205"
				r="1" g="1" b="1" a="1"
				nx="-2.43359" ny="-0.366968" nz="2.67216"
				u="0.249741" v="0.1891">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="0.796203" y="0.476737" z="6.70807"
				r="1" g="1" b="1" a="1"
				nx="0.114621" ny="0.3789" nz="0.918312"
				u="0.249741" v="0.489905">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="3.0859" y="4.70258" z="2.92825"
				r="1" g="1" b="1" a="1"
				nx="0.309498" ny="0.742028" nz="0.594648"
				u="0.00655275" v="0.00352852">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="0.377347" y="3.88992" z="5.35205"
				r="1" g="1" b="1" a="1"
				nx="-2.43359" ny="-0.366968" nz="2.67216"
				u="0.249741" v="0.1891">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="3.0859" y="4.70258" z="2.92825"
				r="1" g="1" b="1" a="1"
				nx="0.309498" ny="0.742028" nz="0.594648"
				u="0.00655275" v="0.00352852">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="-2.95254" y="4.3515" z="3.82352"
				r="1" g="1" b="1" a="1"
				nx="-0.20863" ny="0.712708" nz="0.669717"
				u="0.49293" v="0.00352852">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="0.377347" y="3.88992" z="5.35205"
				r="1" g="1" b="1" a="1"
				nx="-2.43359" ny="-0.366968" nz="2.67216"
				u="0.249741" v="0.1891">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="0.377347" y="3.88992" z="5.35205"
				r="1" g="1" b="1" a="1"
				nx="-2.43359" ny="-0.366968" nz="2.67216"
				u="0.772752" v="0.0160363">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="1.76878" y="4.3074" z="4.10691"
				r="1" g="1" b="1" a="1"
				nx="-0.612997" ny="0.633026" nz="-0.472772"
				u="1.00017" v="0.127542">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="0.21758" y="2.39418" z="3.55646"
				r="1" g="1" b="1" a="1"
				nx="-0.991142" ny="-0.044394" nz="0.12517"
				u="0.772783" v="0.477891">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="1.60816" y="1.7797" z="4.51335"
				r="1" g="1" b="1" a="1"
				nx="-0.645214" ny="-0.335629" nz="0.686332"
				u="0.554576" v="0.127664">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="1.24849" y="2.98186" z="4.7631"
				r="1" g="1" b="1" a="1"
				nx="-0.0564163" ny="-1.78456" nz="3.16379"
				u="0.772752" v="0.0160363">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="0.235577" y="2.39015" z="3.52152"
				r="1" g="1" b="1" a="1"
				nx="-0.657813" ny="-0.312182" nz="0.685437"
				u="0.772783" v="0.477891">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="1.24849" y="2.98186" z="4.7631"
				r="1" g="1" b="1" a="1"
				nx="-0.0564163" ny="-1.78456" nz="3.16379"
				u="0.772752" v="0.0160363">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="0.0119549" y="3.03681" z="5.2051"
				r="1" g="1" b="1" a="1"
				nx="0.0902341" ny="-0.92563" nz="0.367515"
				u="1.00017" v="0.127542">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="0.235577" y="2.39015" z="3.52152"
				r="1" g="1" b="1" a="1"
				nx="-0.657813" ny="-0.312182" nz="0.685437"
				u="0.772783" v="0.477891">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="-1.28505" y="3.09445" z="5.66872"
				r="1" g="1" b="1" a="1"
				nx="0.326078" ny="0.381983" nz="0.864732"
				u="0.49293" v="0.00352852">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="2.00625" y="0.449149" z="4.23692"
				r="1" g="1" b="1" a="1"
				nx="0.715203" ny="0.069501" nz="0.695452"
				u="0.249741" v="0.489905">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="1.24849" y="2.98186" z="4.7631"
				r="1" g="1" b="1" a="1"
				nx="-0.0564163" ny="-1.78456" nz="3.16379"
				u="0.249741" v="0.1891">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="2.00625" y="0.449149" z="4.23692"
				r="1" g="1" b="1" a="1"
				nx="0.715203" ny="0.069501" nz="0.695452"
				u="0.249741" v="0.489905">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="1.57606" y="4.56712" z="2.58236"
				r="1" g="1" b="1" a="1"
				nx="0.663864" ny="0.553957" nz="0.50241"
				u="0.00655275" v="0.00352852">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="1.24849" y="2.98186" z="4.7631"
				r="1" g="1" b="1" a="1"
				nx="-0.0564163" ny="-1.78456" nz="3.16379"
				u="0.249741" v="0.1891">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="1.57606" y="4.56712" z="2.58236"
				r="1" g="1" b="1" a="1"
				nx="0.663864" ny="0.553957" nz="0.50241"
				u="0.00655275" v="0.00352852">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="-1.28505" y="3.09445" z="5.66872"
				r="1" g="1" b="1" a="1"
				nx="0.326078" ny="0.381983" nz="0.864732"
				u="0.49293" v="0.00352852">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="1.24849" y="2.98186" z="4.7631"
				r="1" g="1" b="1" a="1"
				nx="-0.0564163" ny="-1.78456" nz="3.16379"
				u="0.249741" v="0.1891">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="1.24849" y="2.98186" z="4.7631"
				r="1" g="1" b="1" a="1"
				nx="-0.0564163" ny="-1.78456" nz="3.16379"
				u="0.772752" v="0.0160363">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="1.41677" y="3.79623" z="3.64281"
				r="1" g="1" b="1" a="1"
				nx="-0.738811" ny="0.59303" nz="0.320116"
				u="1.00017" v="0.127542">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="0.235577" y="2.39015" z="3.52152"
				r="1" g="1" b="1" a="1"
				nx="-0.657813" ny="-0.312182" nz="0.685437"
				u="0.772783" v="0.477891">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="2.55671" y="1.62722" z="3.79305"
				r="1" g="1" b="1" a="1"
				nx="-0.243832" ny="-0.705641" nz="0.665295"
				u="0.554576" v="0.127664">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="1.67987" y="2.76977" z="4.68352"
				r="1" g="1" b="1" a="1"
				nx="1.54257" ny="-2.23968" nz="2.40869"
				u="0.772752" v="0.0160363">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="0.263917" y="1.84482" z="3.18352"
				r="1" g="1" b="1" a="1"
				nx="-0.263464" ny="-0.689984" nz="0.674173"
				u="0.772783" v="0.477891">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="1.67987" y="2.76977" z="4.68352"
				r="1" g="1" b="1" a="1"
				nx="1.54257" ny="-2.23968" nz="2.40869"
				u="0.772752" v="0.0160363">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="0.384455" y="2.03044" z="5.57849"
				r="1" g="1" b="1" a="1"
				nx="0.516151" ny="-0.855547" nz="0.040332"
				u="1.00017" v="0.127542">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="0.263917" y="1.84482" z="3.18352"
				r="1" g="1" b="1" a="1"
				nx="-0.263464" ny="-0.689984" nz="0.674173"
				u="0.772783" v="0.477891">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="-0.974316" y="1.25495" z="6.51722"
				r="1" g="1" b="1" a="1"
				nx="0.419761" ny="0.301028" nz="0.856261"
				u="0.49293" v="0.00352852">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="3.5272" y="0.362641" z="2.80748"
				r="1" g="1" b="1" a="1"
				nx="0.821796" ny="0.221554" nz="0.524944"
				u="0.249741" v="0.489905">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="1.67987" y="2.76977" z="4.68352"
				r="1" g="1" b="1" a="1"
				nx="1.54257" ny="-2.23968" nz="2.40869"
				u="0.249741" v="0.1891">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="3.5272" y="0.362641" z="2.80748"
				r="1" g="1" b="1" a="1"
				nx="0.821796" ny="0.221554" nz="0.524944"
				u="0.249741" v="0.489905">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="0.446523" y="5.38927" z="2.55356"
				r="1" g="1" b="1" a="1"
				nx="0.547799" ny="0.667746" nz="0.504016"
				u="0.00655275" v="0.00352852">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="1.67987" y="2.76977" z="4.68352"
				r="1" g="1" b="1" a="1"
				nx="1.54257" ny="-2.23968" nz="2.40869"
				u="0.249741" v="0.1891">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="0.446523" y="5.38927" z="2.55356"
				r="1" g="1" b="1" a="1"
				nx="0.547799" ny="0.667746" nz="0.504016"
				u="0.00655275" v="0.00352852">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="-0.974316" y="1.25495" z="6.51722"
				r="1" g="1" b="1" a="1"
				nx="0.419761" ny="0.301028" nz="0.856261"
				u="0.49293" v="0.00352852">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="1.67987" y="2.76977" z="4.68352"
				r="1" g="1" b="1" a="1"
				nx="1.54257" ny="-2.23968" nz="2.40869"
				u="0.249741" v="0.1891">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="1.67987" y="2.76977" z="4.68352"
				r="1" g="1" b="1" a="1"
				nx="1.54257" ny="-2.23968" nz="2.40869"
				u="0.772752" v="0.0160363">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="1.04628" y="4.11546" z="3.58932"
				r="1" g="1" b="1" a="1"
				nx="-0.763624" ny="0.150918" nz="0.627776"
				u="1.00017" v="0.127542">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="0.263917" y="1.84482" z="3.18352"
				r="1" g="1" b="1" a="1"
				nx="-0.263464" ny="-0.689984" nz="0.674173"
				u="0.772783" v="0.477891">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="-1.87223" y="1.52738" z="3.99961"
				r="1" g="1" b="1" a="1"
				nx="-0.222343" ny="-0.974831" nz="-0.0163569"
				u="0.554576" v="0.127664">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="0.0584899" y="1.10723" z="2.79467"
				r="1" g="1" b="1" a="1"
				nx="-0.197326" ny="-0.980296" nz="-0.00903723"
				u="0.772783" v="0.477891">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="-0.537292" y="1.20769" z="4.90596"
				r="1" g="1" b="1" a="1"
				nx="-2.58218" ny="-2.30865" nz="1.09539"
				u="0.772752" v="0.0160363">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="-0.537292" y="1.20769" z="4.90596"
				r="1" g="1" b="1" a="1"
				nx="-2.58218" ny="-2.30865" nz="1.09539"
				u="0.772752" v="0.0160363">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="0.0584899" y="1.10723" z="2.79467"
				r="1" g="1" b="1" a="1"
				nx="-0.197326" ny="-0.980296" nz="-0.00903723"
				u="0.772783" v="0.477891">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="0.0523296" y="-0.349991" z="4.62099"
				r="1" g="1" b="1" a="1"
				nx="-0.920665" ny="-0.303608" nz="-0.245354"
				u="1.00017" v="0.127542">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="0.670793" y="-1.98386" z="4.32209"
				r="1" g="1" b="1" a="1"
				nx="-0.169126" ny="-0.238946" nz="0.956191"
				u="0.49293" v="0.00352852">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="-0.537292" y="1.20769" z="4.90596"
				r="1" g="1" b="1" a="1"
				nx="-2.58218" ny="-2.30865" nz="1.09539"
				u="0.249741" v="0.1891">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="-3.34973" y="1.88121" z="2.99646"
				r="1" g="1" b="1" a="1"
				nx="-0.538636" ny="0.116525" nz="0.834442"
				u="0.249741" v="0.489905">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="-3.34973" y="1.88121" z="2.99646"
				r="1" g="1" b="1" a="1"
				nx="-0.538636" ny="0.116525" nz="0.834442"
				u="0.249741" v="0.489905">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="-0.537292" y="1.20769" z="4.90596"
				r="1" g="1" b="1" a="1"
				nx="-2.58218" ny="-2.30865" nz="1.09539"
				u="0.249741" v="0.1891">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="1.94288" y="3.60546" z="4.36611"
				r="1" g="1" b="1" a="1"
				nx="-0.0545941" ny="0.272734" nz="0.960539"
				u="0.00655275" v="0.00352852">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="1.94288" y="3.60546" z="4.36611"
				r="1" g="1" b="1" a="1"
				nx="-0.0545941" ny="0.272734" nz="0.960539"
				u="0.00655275" v="0.00352852">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="-0.537292" y="1.20769" z="4.90596"
				r="1" g="1" b="1" a="1"
				nx="-2.58218" ny="-2.30865" nz="1.09539"
				u="0.249741" v="0.1891">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="0.670793" y="-1.98386" z="4.32209"
				r="1" g="1" b="1" a="1"
				nx="-0.169126" ny="-0.238946" nz="0.956191"
				u="0.49293" v="0.00352852">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="-0.537292" y="1.20769" z="4.90596"
				r="1" g="1" b="1" a="1"
				nx="-2.58218" ny="-2.30865" nz="1.09539"
				u="0.772752" v="0.0160363">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="0.0584899" y="1.10723" z="2.79467"
				r="1" g="1" b="1" a="1"
				nx="-0.197326" ny="-0.980296" nz="-0.00903723"
				u="0.772783" v="0.477891">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="0.736814" y="2.43947" z="4.62863"
				r="1" g="1" b="1" a="1"
				nx="0.701836" ny="-0.674142" nz="0.230128"
				u="1.00017" v="0.127542">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="-1.25829" y="0.97692" z="4.01183"
				r="1" g="1" b="1" a="1"
				nx="-0.23885" ny="-0.950416" nz="0.199149"
				u="0.554576" v="0.127664">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="-0.10535" y="0.340655" z="2.35812"
				r="1" g="1" b="1" a="1"
				nx="-0.213188" ny="-0.957044" nz="0.196513"
				u="0.772783" v="0.477891">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="0.182802" y="0.678147" z="4.31435"
				r="1" g="1" b="1" a="1"
				nx="-1.98324" ny="-1.96831" nz="2.32162"
				u="0.772752" v="0.0160363">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="0.182802" y="0.678147" z="4.31435"
				r="1" g="1" b="1" a="1"
				nx="-1.98324" ny="-1.96831" nz="2.32162"
				u="0.772752" v="0.0160363">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="-0.10535" y="0.340655" z="2.35812"
				r="1" g="1" b="1" a="1"
				nx="-0.213188" ny="-0.957044" nz="0.196513"
				u="0.772783" v="0.477891">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="0.526689" y="-0.80239" z="4.04594"
				r="1" g="1" b="1" a="1"
				nx="-0.949637" ny="-0.253873" nz="0.18368"
				u="1.00017" v="0.127542">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="0.887394" y="-2.35535" z="3.76439"
				r="1" g="1" b="1" a="1"
				nx="0.226365" ny="-0.122606" nz="0.966295"
				u="0.49293" v="0.00352852">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="0.182802" y="0.678147" z="4.31435"
				r="1" g="1" b="1" a="1"
				nx="-1.98324" ny="-1.96831" nz="2.32162"
				u="0.249741" v="0.1891">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="-2.85331" y="1.30761" z="3.67701"
				r="1" g="1" b="1" a="1"
				nx="-0.149966" ny="0.2462" nz="0.957547"
				u="0.249741" v="0.489905">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="-2.85331" y="1.30761" z="3.67701"
				r="1" g="1" b="1" a="1"
				nx="-0.149966" ny="0.2462" nz="0.957547"
				u="0.249741" v="0.489905">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="0.182802" y="0.678147" z="4.31435"
				r="1" g="1" b="1" a="1"
				nx="-1.98324" ny="-1.96831" nz="2.32162"
				u="0.249741" v="0.1891">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="2.11758" y="2.61767" z="2.68113"
				r="1" g="1" b="1" a="1"
				nx="0.34803" ny="0.375984" nz="0.858784"
				u="0.00655275" v="0.00352852">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="2.11758" y="2.61767" z="2.68113"
				r="1" g="1" b="1" a="1"
				nx="0.34803" ny="0.375984" nz="0.858784"
				u="0.00655275" v="0.00352852">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="0.182802" y="0.678147" z="4.31435"
				r="1" g="1" b="1" a="1"