<?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?>

<!DOCTYPE animation [
	<!ELEMENT animation  (frame+)>
	<!ELEMENT frame      (transform+)>
	<!ELEMENT transform   EMPTY>
	<!ATTLIST frame index CDATA #REQUIRED>
	<!ATTLIST transform name CDATA #REQUIRED>
	<!ATTLIST transform m00 CDATA #REQUIRED>
	<!ATTLIST transform m01 CDATA #REQUIRED>
	<!ATTLIST transform m02 CDATA #REQUIRED>
	<!ATTLIST transform m03 CDATA #REQUIRED>
	<!ATTLIST transform m10 CDATA #REQUIRED>
	<!ATTLIST transform m11 CDATA #REQUIRED>
	<!ATTLIST transform m12 CDATA #REQUIRED>
	<!ATTLIST transform m13 CDATA #REQUIRED>
	<!ATTLIST transform m20 CDATA #REQUIRED>
	<!ATTLIST transform m21 CDATA #REQUIRED>
	<!ATTLIST transform m22 CDATA #REQUIRED>
	<!ATTLIST transform m23 CDATA #REQUIRED>
	<!ATTLIST transform m30 CDATA #REQUIRED>
	<!ATTLIST transform m31 CDATA #REQUIRED>
	<!ATTLIST transform m32 CDATA #REQUIRED>
	<!ATTLIST transform m33 CDATA #REQUIRED>
]>

<animation>
	<frame index="0">
		<transform name="Bip01 Spine"
			m00="-0.203181" m10="1.72709" m20="0.203471" m30="-0.124533"
			m01="-6.22725e-005" m11="-0.198434" m21="1.79426" m31="0.0284109"
			m02="1.77244" m12="0.197975" m22="0.0233876" m32="2.09748"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 Pelvis"
			m00="-0.0879419" m10="1.94897" m20="0.221333" m30="0.127258"
			m01="-0.0156017" m11="-0.222123" m21="1.95185" m31="0.0172161"
			m02="1.96185" m12="0.0855981" m22="0.0254436" m32="0.765777"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 Head"
			m00="-0.172966" m10="1.09751" m20="-0.0848194" m30="-0.25503"
			m01="-0.109549" m11="0.0684269" m21="1.1067" m31="0.0253153"
			m02="1.10052" m12="0.179305" m22="0.0968333" m32="3.47029"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 Neck"
			m00="0.29324" m10="1.25873" m20="0.146551" m30="-0.28978"
			m01="-0.0497575" m11="-0.13887" m21="1.29233" m31="0.0312117"
			m02="1.26625" m12="-0.296954" m22="0.0168438" m32="3.32023"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 Spine1"
			m00="-0.260983" m10="1.66368" m20="0.190953" m30="-0.19708"
			m01="0.00776789" m11="-0.192053" m21="1.68388" m31="0.028443"
			m02="1.67458" m12="0.260175" m22="0.021949" m32="2.72616"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 Tail"
			m00="-0.227832" m10="-1.29334" m20="-0.228468" m30="-0.725999"
			m01="0.0639403" m11="-0.242528" m21="1.30917" m31="0.0804102"
			m02="-1.31181" m12="0.212803" m22="0.103492" m32="3.35126"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 Tail2"
			m00="-0.155158" m10="-1.48683" m20="0.0639779" m30="-0.916272"
			m01="0.160433" m11="0.0472383" m21="1.48689" m31="0.246759"
			m02="-1.47953" m12="0.161045" m22="0.154522" m32="2.16255"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 L Thigh"
			m00="-0.0967893" m10="1.24672" m20="-0.0393983" m30="0.212253"
			m01="-0.336261" m11="-0.060891" m21="-1.20916" m31="0.766743"
			m02="-1.2953" m12="-0.0773519" m22="0.316843" m32="0.775547"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 R Thigh"
			m00="0.324985" m10="1.21039" m20="-0.0849354" m30="0.0422628"
			m01="0.0190694" m11="-0.091959" m21="-1.24709" m31="-0.732311"
			m02="-1.30164" m12="0.300855" m22="-0.0394763" m32="0.756008"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 Tail1"
			m00="-0.202822" m10="-1.4091" m20="0.157675" m30="-0.826707"
			m01="0.310685" m11="0.109975" m21="1.39335" m31="0.108773"
			m02="-1.36403" m12="0.234573" m22="0.293919" m32="2.76849"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 L Clavicle"
			m00="-0.119364" m10="-1.24207" m20="-0.195478" m30="-0.312896"
			m01="1.25712" m11="-0.12174" m21="0.0059028" m31="0.280587"
			m02="-0.0246466" m12="-0.194008" m22="1.24778" m32="3.31538"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 L UpperArm"
			m00="0.000157941" m10="-0.843828" m20="0.880257" m30="-0.35615"
			m01="1.72328" m11="-0.135862" m21="-0.130389" m31="0.736138"
			m02="0.269356" m12="0.869709" m22="0.833693" m32="3.30645"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 L Forearm"
			m00="1.16103" m10="-0.176924" m20="0.890158" m30="-0.356071"
			m01="0.538472" m11="1.1633" m21="-0.131855" m31="1.61367"
			m02="-1.14166" m12="0.368747" m22="0.843071" m32="3.44361"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 L Hand"
			m00="0.532028" m10="-0.987248" m20="0.47299" m30="0.172329"
			m01="-0.874449" m11="-0.0619331" m21="0.846598" m31="1.85874"
			m02="-0.665749" m12="-0.707612" m22="-0.734004" m32="2.92403"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 L Finger1"
			m00="-0.963318" m10="-0.580707" m20="0.470427" m30="0.412032"
			m01="0.00460061" m11="0.76098" m21="0.948736" m31="1.46476"
			m02="-0.750291" m12="0.750265" m22="-0.59817" m32="2.62408"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 L Finger0"
			m00="-0.965772" m10="0.10849" m20="0.736243" m30="0.0577392"
			m01="-0.682102" m11="0.362998" m21="-0.941191" m31="1.40536"
			m02="-0.304904" m12="-1.15571" m22="-0.226509" m32="3.0014"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 L Finger01"
			m00="0.182122" m10="0.95091" m20="0.736242" m30="-0.236731"
			m01="0.415301" m11="0.649809" m21="-0.941195" m31="1.19739"
			m02="-1.13371" m12="0.390799" m22="-0.226512" m32="2.90843"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 L Finger11"
			m00="-0.559376" m10="0.973372" m20="0.470427" m30="0.123107"
			m01="0.763654" m11="-0.0231029" m21="0.948736" m31="1.46614"
			m02="0.77128" m12="0.728849" m22="-0.598168" m32="2.39905"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 R Clavicle"
			m00="-0.397705" m10="-1.18272" m20="0.195478" m30="-0.368124"
			m01="-1.19742" m11="0.401674" m21="-0.00590271" m31="-0.206449"
			m02="-0.0566401" m12="-0.187185" m22="-1.24778" m32="3.30904"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 R UpperArm"
			m00="-0.47837" m10="-1.05017" m20="-0.521721" m30="-0.512244"
			m01="-1.66868" m11="0.352989" m21="0.0372592" m31="-0.640368"
			m02="0.170131" m12="0.509347" m22="-1.10151" m32="3.28851"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 R Forearm"
			m00="1.40731" m10="-0.467292" m20="-0.52759" m30="-0.755839"
			m01="-0.696128" m11="-1.12632" m21="0.0376779" m31="-1.49009"
			m02="-0.690107" m12="0.183229" m22="-1.1139" m32="3.37515"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 R Hand"
			m00="0.631867" m10="-0.911442" m20="-0.502368" m30="-0.115359"
			m01="0.79921" m11="0.0434484" m21="0.918479" m31="-1.80691"
			m02="-0.673015" m12="-0.804112" m22="0.619052" m32="3.06107"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 R Finger1"
			m00="-0.886563" m10="-0.683246" m20="-0.48227" m30="0.169323"
			m01="-0.0270699" m11="-0.677738" m21="1.00953" m31="-1.44683"
			m02="-0.839175" m12="0.743678" m22="0.476944" m32="2.75785"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 R Finger0"
			m00="-0.900658" m10="0.201863" m20="-0.796032" m30="-0.21633"
			m01="0.69193" m11="-0.455974" m21="-0.89235" m31="-1.3449"
			m02="-0.448306" m12="-1.1093" m22="0.221941" m32="3.09296"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 R Finger01"
			m00="0.270637" m10="0.879144" m20="-0.796034" m30="-0.490946"
			m01="-0.509124" m11="-0.65249" m21="-0.892346" m31="-1.13393"
			m02="-1.07633" m12="0.529687" m22="0.221938" m32="2.95627"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 R Finger11"
			m00="-0.664168" m10="0.899441" m20="-0.482271" m30="-0.0965795"
			m01="-0.679557" m11="0.0434584" m21="1.00953" m31="-1.45495"
			m02="0.766827" m12="0.817512" m22="0.476947" m32="2.50616"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 R Calf"
			m00="-0.996969" m10="0.780067" m20="-0.0862123" m30="0.12939"
			m01="0.0925511" m11="-0.0214348" m21="-1.26584" m31="-0.727198"
			m02="-0.778746" m12="-1.00121" m22="-0.0400697" m32="0.407045"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 R Foot"
			m00="9.84628e-007" m10="1.06437" m20="-0.626322" m30="-0.0291823"
			m01="-5.47544e-007" m11="-0.639731" m21="-1.04206" m31="-0.712478"
			m02="-1.261" m12="1.01952e-006" m22="0.0" m32="0.283182"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 R Toe0"
			m00="1.08164" m10="-1.02314e-006" m20="-0.650111" m30="0.507979"
			m01="-0.65011" m11="5.75918e-007" m21="-1.08163" m31="-1.03534"
			m02="9.97198e-007" m12="1.26197" m22="0.0" m32="0.0137593"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 L Foot"
			m00="1.3581e-007" m10="1.12217" m20="0.520694" m30="0.0458626"
			m01="1.88178e-007" m11="0.531843" m21="-1.09865" m31="0.644177"
			m02="-1.261" m12="0.0" m22="0.0" m32="0.287112"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 L Calf"
			m00="-0.882978" m10="0.910472" m20="-0.0399906" m30="0.186304"
			m01="-0.203804" m11="-0.251855" m21="-1.22734" m31="0.676593"
			m02="-0.887565" m12="-0.847935" m22="0.321606" m32="0.428283"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 L Toe0"
			m00="1.14038" m10="-2.14978e-007" m20="0.540471" m30="0.612198"
			m01="0.540472" m11="-2.75539e-007" m21="-1.14038" m31="0.912586"
			m02="-2.51025e-007" m12="1.26197" m22="0.0" m32="0.0176891"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 Ponytail1"
			m00="1.49943" m10="0.23091" m20="-0.121447" m30="0.00131361"
			m01="0.138396" m11="-0.10337" m21="1.51212" m31="-0.00371385"
			m02="0.22117" m12="-1.50078" m22="-0.122836" m32="4.02719"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 Ponytail2"
			m00="1.90495" m10="0.011352" m20="-0.0789131" m30="0.140949"
			m01="0.0772102" m11="-0.0800265" m21="1.96481" m31="0.0395035"
			m02="0.0115855" m12="-1.33332" m22="-0.1186" m32="3.65578"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 Ponytail21"
			m00="2.02635" m10="0.0906407" m20="-0.318758" m30="0.733775"
			m01="0.347392" m11="-0.327153" m21="1.95094" m31="0.0636653"
			m02="0.0577893" m12="-1.21169" m22="-0.550594" m32="3.65988"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 Prop1"
			m00="0.0834061" m10="-0.94258" m20="-0.323398" m30="0.835197"
			m01="0.993647" m11="0.103271" m21="-0.0447279" m31="0.0373661"
			m02="0.0755573" m12="-0.317613" m22="0.945205" m32="0.763076"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 Prop2"
			m00="-0.124169" m10="0.132469" m20="-0.983379" m30="1.65513"
			m01="0.98297" m11="-0.11888" m21="-0.140131" m31="-0.0374225"
			m02="-0.135467" m12="-0.984032" m22="-0.115452" m32="1.37118"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 Prop3"
			m00="0.149555" m10="-0.149535" m20="-0.97738" m30="1.75621"
			m01="-0.987044" m11="0.0355287" m21="-0.156469" m31="0.0446217"
			m02="0.0581227" m12="0.988118" m22="-0.142284" m32="1.41725"
			m03="0" m13="0" m23="0" m33="1"/>
	</frame>
	<frame index="1">
		<transform name="Bip01 Spine"
			m00="-0.203406" m10="1.72706" m20="0.203471" m30="-0.127692"
			m01="-3.63592e-005" m11="-0.198434" m21="1.79426" m31="0.0283315"
			m02="1.77241" m12="0.198198" m22="0.0233876" m32="2.09754"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 Pelvis"
			m00="-0.0878178" m10="1.94898" m20="0.221333" m30="0.124015"
			m01="-0.0156158" m11="-0.222122" m21="1.95185" m31="0.0171465"
			m02="1.96186" m12="0.0854732" m22="0.0254436" m32="0.765823"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 Head"
			m00="-0.172897" m10="1.09752" m20="-0.0848147" m30="-0.258505"
			m01="-0.109557" m11="0.068426" m21="1.1067" m31="0.0252721"
			m02="1.10053" m12="0.179236" m22="0.0968466" m32="3.47032"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 Neck"
			m00="0.292837" m10="1.25882" m20="0.146551" m30="-0.293207"
			m01="-0.0497132" m11="-0.138886" m21="1.29233" m31="0.0311633"
			m02="1.26635" m12="-0.296549" m22="0.0168438" m32="3.32025"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 Spine1"
			m00="-0.261515" m10="1.66359" m20="0.190953" m30="-0.200318"
			m01="0.00782932" m11="-0.192051" m21="1.68388" m31="0.0283728"
			m02="1.6745" m12="0.26071" m22="0.021949" m32="2.72621"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 Tail"
			m00="-0.231755" m10="-1.29265" m20="-0.228463" m30="-0.729078"
			m01="0.063229" m11="-0.242719" m21="1.30917" m31="0.0803214"
			m02="-1.31116" m12="0.216778" m22="0.103515" m32="3.35136"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 Tail2"
			m00="-0.150248" m10="-1.4873" m20="0.0645813" m30="-0.920979"
			m01="0.159086" m11="0.0484975" m21="1.487" m31="0.245875"
			m02="-1.48018" m12="0.156183" m22="0.153263" m32="2.16282"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 L Thigh"
			m00="-0.0839076" m10="1.24753" m20="-0.0395089" m30="0.20901"
			m01="-0.336439" m11="-0.0579562" m21="-1.20926" m31="0.766673"
			m02="-1.29615" m12="-0.0657163" m22="0.316442" m32="0.775593"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 R Thigh"
			m00="0.334941" m10="1.20802" m20="-0.0850438" m30="0.0390199"
			m01="0.0190593" m11="-0.0923833" m21="-1.24706" m31="-0.732381"
			m02="-1.29911" m12="0.310099" m22="-0.0402219" m32="0.756053"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 Tail1"
			m00="-0.202563" m10="-1.40907" m20="0.158226" m30="-0.831529"
			m01="0.309609" m11="0.110761" m21="1.39353" m31="0.108368"
			m02="-1.36431" m12="0.234345" m22="0.292749" m32="2.76888"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 L Clavicle"
			m00="-0.119351" m10="-1.24201" m20="-0.195874" m30="-0.31632"
			m01="1.25712" m11="-0.121741" m21="0.00594866" m31="0.280538"
			m02="-0.0247298" m12="-0.194398" m22="1.24772" m32="3.31539"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 L UpperArm"
			m00="0.000334179" m10="-0.843859" m20="0.880228" m30="-0.35957"
			m01="1.72326" m11="-0.135863" m21="-0.13057" m31="0.736089"
			m02="0.269536" m12="0.869679" m22="0.833696" m32="3.30643"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 L Forearm"
			m00="1.16111" m10="-0.17681" m20="0.890128" m30="-0.3594"
			m01="0.538467" m11="1.16328" m21="-0.132039" m31="1.61361"
			m02="-1.14159" m12="0.368866" m22="0.843074" m32="3.44368"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 L Hand"
			m00="0.532239" m10="-0.987023" m20="0.473226" m30="0.169036"
			m01="-0.874476" m11="-0.061951" m21="0.846567" m31="1.85867"
			m02="-0.665549" m12="-0.707922" m22="-0.733885" m32="2.92413"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 L Finger1"
			m00="-0.963081" m10="-0.580947" m20="0.470618" m30="0.408832"
			m01="0.00458408" m11="0.761007" m21="0.94871" m31="1.46468"
			m02="-0.750596" m12="0.750052" m22="-0.598058" m32="2.62428"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 L Finger0"
			m00="-0.965677" m10="0.108858" m20="0.736317" m30="0.054419"
			m01="-0.682102" m11="0.362959" m21="-0.941202" m31="1.4053"
			m02="-0.305183" m12="-1.15569" m22="-0.226239" m32="3.00148"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 L Finger01"
			m00="0.182483" m10="0.950795" m20="0.736318" m30="-0.240022"
			m01="0.415262" m11="0.649812" m21="-0.941201" m31="1.19732"
			m02="-1.13367" m12="0.391074" m22="-0.226239" m32="2.90843"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 L Finger11"
			m00="-0.559629" m10="0.973143" m20="0.470618" m30="0.119979"
			m01="0.76368" m11="-0.0230935" m21="0.948709" m31="1.46606"
			m02="0.77107" m12="0.729156" m22="-0.598061" m32="2.39915"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 R Clavicle"
			m00="-0.397691" m10="-1.18266" m20="0.195874" m30="-0.371549"
			m01="-1.19743" m11="0.401673" m21="-0.00594857" m31="-0.206497"
			m02="-0.0567233" m12="-0.187575" m22="-1.24772" m32="3.30904"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 R UpperArm"
			m00="-0.478272" m10="-1.05019" m20="-0.521724" m30="-0.515664"
			m01="-1.66868" m11="0.353003" m21="0.0370704" m31="-0.640417"
			m02="0.170372" m12="0.509296" m22="-1.10151" m32="3.28849"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 R Forearm"
			m00="1.40734" m10="-0.467224" m20="-0.527592" m30="-0.75921"
			m01="-0.696149" m11="-1.12632" m21="0.0374874" m31="-1.49014"
			m02="-0.690007" m12="0.183392" m22="-1.1139" m32="3.37524"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 R Hand"
			m00="0.63208" m10="-0.911184" m20="-0.502562" m30="-0.118712"
			m01="0.799184" m11="0.0434257" m21="0.918507" m31="-1.80697"
			m02="-0.672843" m12="-0.804404" m22="0.618859" m32="3.06121"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 R Finger1"
			m00="-0.886294" m10="-0.683479" m20="-0.482417" m30="0.166068"
			m01="-0.0270915" m11="-0.677711" m21="1.00955" m31="-1.4469"
			m02="-0.839458" m12="0.743487" m22="0.47675" m32="2.75807"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 R Finger0"
			m00="-0.900511" m10="0.202211" m20="-0.7961" m30="-0.219691"
			m01="0.691924" m11="-0.456014" m21="-0.892341" m31="-1.34496"
			m02="-0.448622" m12="-1.10922" m22="0.221722" m32="3.09305"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 R Finger01"
			m00="0.270973" m10="0.878964" m20="-0.796099" m30="-0.494263"
			m01="-0.509163" m11="-0.652483" m21="-0.892342" m31="-1.13399"
			m02="-1.07623" m12="0.529995" m22="0.221722" m32="2.95627"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 R Finger11"
			m00="-0.664403" m10="0.899177" m20="-0.482417" m30="-0.0997544"
			m01="-0.679533" m11="0.0434745" m21="1.00955" m31="-1.45503"
			m02="0.766645" m12="0.817802" m22="0.476749" m32="2.50629"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 R Calf"
			m00="-0.993361" m10="0.784651" m20="-0.0863221" m30="0.128816"
			m01="0.0930065" m11="-0.0213331" m21="-1.26581" m31="-0.727271"
			m02="-0.783289" m12="-0.997622" m22="-0.0408265" m32="0.407767"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 R Foot"
			m00="8.06143e-007" m10="1.06437" m20="-0.626321" m30="-0.0291823"
			m01="-5.25852e-007" m11="-0.639732" m21="-1.04206" m31="-0.712478"
			m02="-1.261" m12="1.02643e-006" m22="0.0" m32="0.283182"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 R Toe0"
			m00="1.08164" m10="-7.75576e-007" m20="-0.65011" m30="0.507979"
			m01="-0.650111" m11="6.26346e-007" m21="-1.08164" m31="-1.03534"
			m02="1.14769e-006" m12="1.26197" m22="-1.77542e-007" m32="0.0137593"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 L Foot"
			m00="0.0" m10="1.12217" m20="0.520694" m30="0.0458627"
			m01="0.0" m11="0.531842" m21="-1.09865" m31="0.644177"
			m02="-1.261" m12="1.33138e-007" m22="0.0" m32="0.287112"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 L Calf"
			m00="-0.884302" m10="0.909179" m20="-0.0401028" m30="0.186514"
			m01="-0.203067" m11="-0.251949" m21="-1.22744" m31="0.676476"
			m02="-0.886416" m12="-0.849292" m22="0.321199" m32="0.4281"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 L Toe0"
			m00="1.14038" m10="1.6237e-007" m20="0.540472" m30="0.612198"
			m01="0.540471" m11="0.0" m21="-1.14038" m31="0.912586"
			m02="2.56436e-007" m12="1.26197" m22="0.0" m32="0.017689"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 Ponytail1"
			m00="1.49865" m10="0.235904" m20="-0.121457" m30="-0.00212715"
			m01="0.138744" m11="-0.102888" m21="1.51212" m31="-0.0037609"
			m02="0.22617" m12="-1.50004" m22="-0.122818" m32="4.0272"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 Ponytail2"
			m00="1.90493" m10="0.0125456" m20="-0.078924" m30="0.137485"
			m01="0.0773191" m11="-0.079965" m21="1.96481" m31="0.0394593"
			m02="0.0132873" m12="-1.33331" m22="-0.118581" m32="3.65579"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 Ponytail21"
			m00="2.02628" m10="0.0917409" m20="-0.318385" m30="0.730306"
			m01="0.347504" m11="-0.327092" m21="1.95095" m31="0.0636555"
			m02="0.0596113" m12="-1.21162" m22="-0.550789" m32="3.66042"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 Prop1"
			m00="0.0833863" m10="-0.942479" m20="-0.323699" m30="0.832582"
			m01="0.993649" m11="0.103264" m21="-0.0446925" m31="0.0372208"
			m02="0.0755479" m12="-0.317916" m22="0.945104" m32="0.763455"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 Prop2"
			m00="-0.124121" m10="0.132781" m20="-0.983343" m30="1.65232"
			m01="0.982966" m11="-0.118916" m21="-0.140131" m31="-0.0375494"
			m02="-0.135542" m12="-0.983986" m22="-0.115759" m32="1.37182"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 Prop3"
			m00="0.149532" m10="-0.149849" m20="-0.977336" m30="1.75338"
			m01="-0.987042" m11="0.035565" m21="-0.15647" m31="0.044496"
			m02="0.0582058" m12="0.988069" m22="-0.142589" m32="1.41792"
			m03="0" m13="0" m23="0" m33="1"/>
	</frame>
	<frame index="2">
		<transform name="Bip01 Spine"
			m00="-0.204085" m10="1.72699" m20="0.203471" m30="-0.130846"
			m01="4.16161e-005" m11="-0.198434" m21="1.79426" m31="0.0282288"
			m02="1.77234" m12="0.198868" m22="0.0233876" m32="2.09772"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 Pelvis"
			m00="-0.0874441" m10="1.949" m20="0.221333" m30="0.120607"
			m01="-0.0156584" m11="-0.222119" m21="1.95185" m31="0.0170732"
			m02="1.96187" m12="0.0850973" m22="0.0254436" m32="0.76596"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 Head"
			m00="-0.172687" m10="1.09756" m20="-0.0847987" m30="-0.262612"
			m01="-0.109581" m11="0.068425" m21="1.1067" m31="0.0252786"
			m02="1.10056" m12="0.179028" m22="0.0968866" m32="3.47042"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 Neck"
			m00="0.291625" m10="1.2591" m20="0.146551" m30="-0.29717"
			m01="-0.0495795" m11="-0.138934" m21="1.29233" m31="0.0311539"
			m02="1.26663" m12="-0.29533" m22="0.0168438" m32="3.32032"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 Spine1"
			m00="-0.263116" m10="1.66334" m20="0.190953" m30="-0.203713"
			m01="0.00801415" m11="-0.192044" m21="1.68388" m31="0.0282978"
			m02="1.67425" m12="0.262322" m22="0.021949" m32="2.72637"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 Tail"
			m00="-0.23612" m10="-1.29186" m20="-0.228446" m30="-0.731994"
			m01="0.0624835" m11="-0.242928" m21="1.30917" m31="0.0801903"
			m02="-1.31041" m12="0.221193" m22="0.103587" m32="3.35166"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 Tail2"
			m00="-0.145163" m10="-1.48778" m20="0.0652411" m30="-0.925785"
			m01="0.157653" m11="0.0498291" m21="1.48711" m31="0.244907"
			m02="-1.48084" m12="0.151149" m22="0.151925" m32="2.16333"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 L Thigh"
			m00="-0.0708666" m10="1.24823" m20="-0.0395958" m30="0.205601"
			m01="-0.336503" m11="-0.0549611" m21="-1.20939" m31="0.7666"
			m02="-1.29692" m12="-0.053946" m22="0.315956" m32="0.775729"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 R Thigh"
			m00="0.345109" m10="1.20552" m20="-0.0851482" m30="0.0356117"
			m01="0.0190613" m11="-0.0928203" m21="-1.24703" m31="-0.732454"
			m02="-1.29645" m12="0.319541" m22="-0.0410007" m32="0.75619"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 Tail1"
			m00="-0.202454" m10="-1.40902" m20="0.158848" m30="-0.836384"
			m01="0.308471" m11="0.111593" m21="1.39372" m31="0.107906"
			m02="-1.36458" m12="0.234273" m22="0.291492" m32="2.76951"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 L Clavicle"
			m00="-0.119312" m10="-1.24183" m20="-0.197067" m30="-0.320276"
			m01="1.25712" m11="-0.121747" m21="0.0060863" m31="0.280529"
			m02="-0.0249803" m12="-0.195572" m22="1.24753" m32="3.31541"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 L UpperArm"
			m00="0.000867988" m10="-0.843952" m20="0.880138" m30="-0.363512"
			m01="1.72317" m11="-0.135868" m21="-0.131113" m31="0.736079"
			m02="0.270079" m12="0.869588" m22="0.833705" m32="3.30636"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 L Forearm"
			m00="1.16135" m10="-0.17646" m20="0.890038" m30="-0.36307"
			m01="0.538458" m11="1.16322" m21="-0.132588" m31="1.61356"
			m02="-1.14135" m12="0.369222" m22="0.843083" m32="3.44389"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 L Hand"
			m00="0.532863" m10="-0.986347" m20="0.473939" m30="0.165474"
			m01="-0.874555" m11="-0.0620168" m21="0.846483" m31="1.85861"
			m02="-0.664944" m12="-0.708859" m22="-0.733523" m32="2.92444"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 L Finger1"
			m00="-0.962363" m10="-0.581653" m20="0.471203" m30="0.405552"
			m01="0.00451244" m11="0.761097" m21="0.948641" m31="1.46459"
			m02="-0.751517" m12="0.749413" m22="-0.597709" m32="2.62486"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 L Finger0"
			m00="-0.965394" m10="0.109968" m20="0.73652" m30="0.0507775"
			m01="-0.682126" m11="0.362831" m21="-0.941237" m31="1.40525"
			m02="-0.306033" m12="-1.15563" m22="-0.225433" m32="3.00173"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 L Finger01"
			m00="0.183573" m10="0.950427" m20="0.73652" m30="-0.243577"
			m01="0.415137" m11="0.649845" m21="-0.941236" m31="1.19727"
			m02="-1.13354" m12="0.391913" m22="-0.225433" m32="2.90842"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 L Finger11"
			m00="-0.560354" m10="0.972445" m20="0.471203" m30="0.116914"
			m01="0.763773" m11="-0.0230222" m21="0.94864" m31="1.46594"
			m02="0.770452" m12="0.730088" m22="-0.597709" m32="2.39946"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 R Clavicle"
			m00="-0.397652" m10="-1.18247" m20="0.197067" m30="-0.375505"
			m01="-1.19743" m11="0.401667" m21="-0.00608622" m31="-0.206507"
			m02="-0.0569736" m12="-0.18875" m22="-1.24753" m32="3.30906"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 R UpperArm"
			m00="-0.477982" m10="-1.05025" m20="-0.521732" m30="-0.519605"
			m01="-1.66869" m11="0.353041" m21="0.036501" m31="-0.640427"
			m02="0.171099" m12="0.509145" m22="-1.10153" m32="3.28841"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 R Forearm"
			m00="1.40746" m10="-0.467029" m20="-0.5276" m30="-0.763003"
			m01="-0.696203" m11="-1.12632" m21="0.0369117" m31="-1.49016"
			m02="-0.689707" m12="0.183883" m22="-1.11392" m32="3.37554"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 R Hand"
			m00="0.632735" m10="-0.910414" m20="-0.503142" m30="-0.122451"
			m01="0.799103" m11="0.0433492" m21="0.918578" m31="-1.80701"
			m02="-0.672326" m12="-0.805279" m22="0.618279" m32="3.06165"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 R Finger1"
			m00="-0.885491" m10="-0.6842" m20="-0.482861" m30="0.162624"
			m01="-0.0271727" m11="-0.67762" m21="1.00961" m31="-1.44698"
			m02="-0.840302" m12="0.742907" m22="0.476181" m32="2.75874"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 R Finger0"
			m00="-0.900074" m10="0.203268" m20="-0.796325" m30="-0.223455"
			m01="0.691884" m11="-0.456136" m21="-0.892305" m31="-1.34499"
			m02="-0.449556" m12="-1.10898" m22="0.221057" m32="3.09334"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 R Finger01"
			m00="0.271998" m10="0.878452" m20="-0.796326" m30="-0.497892"
			m01="-0.509282" m11="-0.652433" m21="-0.892304" m31="-1.13403"
			m02="-1.07591" m12="0.530905" m22="0.221057" m32="2.95627"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 R Finger11"
			m00="-0.665148" m10="0.898396" m20="-0.482862" m30="-0.102958"
			m01="-0.679438" m11="0.0435542" m21="1.00961" m31="-1.45513"
			m02="0.766083" m12="0.818655" m22="0.476182" m32="2.50671"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 R Calf"
			m00="-0.989074" m10="0.790045" m20="-0.0864281" m30="0.128134"
			m01="0.0934644" m11="-0.0212846" m21="-1.26577" m31="-0.727343"
			m02="-0.788641" m12="-0.993358" m22="-0.041617" m32="0.408619"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 R Foot"
			m00="7.8053e-007" m10="1.06437" m20="-0.626322" m30="-0.0291824"
			m01="-4.47083e-007" m11="-0.639731" m21="-1.04206" m31="-0.712478"
			m02="-1.261" m12="9.29335e-007" m22="0.0" m32="0.283182"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 R Toe0"
			m00="1.08164" m10="-8.77679e-007" m20="-0.65011" m30="0.507979"
			m01="-0.650111" m11="6.31252e-007" m21="-1.08164" m31="-1.03534"
			m02="1.1553e-006" m12="1.26197" m22="0.0" m32="0.0137593"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 L Foot"
			m00="2.36271e-007" m10="1.12217" m20="0.520694" m30="0.0458626"
			m01="3.64146e-007" m11="0.531842" m21="-1.09865" m31="0.644177"
			m02="-1.261" m12="0.0" m22="2.02088e-007" m32="0.287112"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 L Calf"
			m00="-0.884856" m10="0.908635" m20="-0.040191" m30="0.186602"
			m01="-0.202498" m11="-0.251794" m21="-1.22756" m31="0.676385"
			m02="-0.885992" m12="-0.849921" m22="0.320705" m32="0.428033"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 L Toe0"
			m00="1.14038" m10="0.0" m20="0.540471" m30="0.612198"
			m01="0.540471" m11="-5.62752e-007" m21="-1.14038" m31="0.912586"
			m02="-3.06427e-007" m12="1.26197" m22="3.75667e-007" m32="0.0176891"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 Ponytail1"
			m00="1.49784" m10="0.240947" m20="-0.121484" m30="-0.00612898"
			m01="0.139108" m11="-0.102361" m21="1.51212" m31="-0.00376594"
			m02="0.231219" m12="-1.49927" m22="-0.122762" m32="4.02725"
			m03="0" m13="0" m23="0" m33="1"/>
		<transform name="Bip01 Ponytail2"
			m00="1.90487" m10="0.0161275" m20="-0.0789505" m30="0.133412"
			m01="0.0776519" m11="-0.0797801" m21="1.96481" m31="0.0394627"